CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date);

SELECT FIRSTNAME, LASTNAME, WEIGHT, BIRTHDATE FROM PLAYERS WHERE WEIGHT > 200;

SELECT FIRSTSEASON, COUNT(ID) FROM PLAYERS GROUP BY FIRSTSEASON;

SELECT FIRSTNAME, LASTNAME, FIRSTSEASON, LASTSEASON FROM PLAYERS WHERE LASTSEASON - FIRSTSEASON > 5;

SELECT EXPERIENCE, COUNT(ID) 
FROM 
    (SELECT ID, FIRSTNAME, LASTNAME, (LASTSEASON - FIRSTSEASON) AS EXPERIENCE 
    FROM PLAYERS) 
GROUP BY EXPERIENCE;
